name: Deploy and build page

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout StarWarsAtari
        uses: actions/checkout@v3
        with:
          path: "./StarWarsAtari"
      - name: Checkout 3d-game-engine-canvas
        uses: actions/checkout@v3
        with:
          repository: jaanonim/3d-game-engine-canvas
          path: "./3d-game-engine-canvas"
      - name: Build
        run: |
          cd "./StarWarsAtari"
          npm i
          npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./StarWarsAtari/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
